name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -e ".[test]"
      - name: Lint with flake8
        run: |
          flake8 dali --count --show-source --statistics
      - name: Test with pytest
        run: |
          pytest dali/tests
      - name: Run driver tests
        run: |
          pip install pymodbus pyusb
          pytest dali/driver/tests
